obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.25
inflation_radius: 0.5

observation_sources: laser

laser:
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true

# Katmanlar
plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

