local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  rolling_window: true
  update_frequency: 5.0
  width: 5.0
  height: 5.0
  resolution: 0.05

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

